# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0008_userprofile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
