# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_workout_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
